x = """1. ABIGAIL RAYHANUN HALA
2. AFIATI NUR LISA RAMADHANI
3. AHMAD SUHADAK
4. ALNABIEF LINTANG WIBOWO
5. ASYRAF ZAHIRUL UBAID
6. AZIZ MUHAMMAD ZAKARIYYA
7. BARRACK QOLBY ALMUFARIED
8. BERLIAN VANIA FEBRIYANTI
9. DINDA AYU AGUSTIN
10. FADILLA PUTRI IRAWAN
11. FARAH HAMIDAH HANDOKO
12. FARHAN RIZQI ARIANTO
13. Fathimah Aqilah Zarrah
14. GHENES GENTHA PRAMESTHI
15. GUSTI RAYZELL MOZART AL FAREL
16. GWEN KEZHIA RAHMAH
17. Janeeta Laura
18. JAZILAH
19. MARCELLO RAMA PUTRA TURNIP
20. MAULIDYA GITHA PERMATA HATI
21. MOH. HASANI
22. MUHAMMAD ALDI SAPUTRA
23. MUHAMMAD RIDHO PRAYOGA
24. Nadin Aishwara Ramadani
25. Najwa Nauraa Arienza Himawan
26. NORFADILA
27. PASHA PUTRA WAHYU MURTIYANSYAH
28. PUTRI ASHINAFIE RAHMATIKA APRILIA
29. R. DIMAS MAULANA ADHIKARA
30. RASCHI CAMILO AFLAH EACYCANDRA
31. ROSIANA WINOTO
32. RUBINA KHAIRUNNISA
33. SAVIRA NURUL HIDAYAH
34. SEPTIAN RAHMAD MAULANA
35. TIO RIZALDI"""

print(x.lower())